### ISSUE TITLE
删我Issues干嘛呢？您是真的忽略了懒得写说明，还是故意给别人留的坑呢？

### ISSUE THREAD

**Issue by TD-wzw** [lcy0604/EraseNet#13]

**Comment by lcy0604** [comment]
你自己不好好看说明，关于数据集的格式，我清清楚楚写明白了吧，也在repo里给了样例，自己没看搞反了mask就diss别人恶心至极？别人发email过来问我也会告知应该咋去生成。你的issue喷的莫名其妙我看了不舒服删了咋的。
还有关于别人issue没回，都是关于预训练模型，你就说我在readme里给没给吧。

wzx___ ***@***.***> 于2022年11月1日周二 10:20写道：
