### ISSUE TITLE
predict the results

### ISSUE THREAD

**Issue by Aspen0309** [lcy0604/EraseNet#14]
![image](https://user-images.githubusercontent.com/126053393/221784883-ef641d34-66f5-4c3f-8555-936c0a90eadb.png)
why the model will output mask-like image? i need your help

**Comment by lcy0604** [comment]
Sry, I do not find this bug in my output on SCUT-Syn using the same code,
and my results are normal.  And I find your results seem to contain some
input images, such as img_59.png and img_94.  Maybe there exist some
mistakes in your input data or the training process?

Aspen0309 ***@***.***> 于2023年2月28日周二 15:38写道：

**Comment by Neyleer** [comment]
I have the same question,how did you solve it. Thanks.

**Comment by sch-123** [comment]
May I ask for the password for SCUT EnsText
