### ISSUE TITLE
我的结果里出现了mask

### ISSUE THREAD

**Issue by Neyleer** [lcy0604/EraseNet#17]
![image](https://github.com/lcy0604/EraseNet/assets/65115838/2aaa559a-5630-45ef-b4d5-6b3b352d4b86)

**Comment by Neyleer** [comment]
阅读了代码后发现，原来dataroot指的应该是all_images而不是外面的

**Comment by Sleepybear66** [comment]
> 阅读了代码后发现，原来dataroot指的应该是all_images而不是外面的
你好，我想问下你的掩码是怎么生成的，可以给出具体的实现方法吗？十分感谢！！！

**Comment by AWangji** [comment]
> ![image](https://private-user-images.githubusercontent.com/65115838/265494746-2aaa559a-5630-45ef-b4d5-6b3b352d4b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTcxMTYsIm5iZiI6MTcyNDgxNjgxNiwicGF0aCI6Ii82NTExNTgzOC8yNjU0OTQ3NDYtMmFhYTU1OWEtNTYzMC00NWVmLWI0ZDUtNmIzYjM1MmQ0Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzNDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDJmYmVkZTQ1ZTU4ZjdmYzhhNzI5YTk4MzFlY2E1YjYxOGQ2MGZkMzhjYzFkN2U0ZTM5YjBkNjA4ODFmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnfGkSWR0wrVH4sGvnGZtnA60mc1omDGBGJDWezbL_0)

同，老哥解决了吗

**Comment by codeporter76** [comment]
> > ![image](https://private-user-images.githubusercontent.com/65115838/265494746-2aaa559a-5630-45ef-b4d5-6b3b352d4b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTcxMTYsIm5iZiI6MTcyNDgxNjgxNiwicGF0aCI6Ii82NTExNTgzOC8yNjU0OTQ3NDYtMmFhYTU1OWEtNTYzMC00NWVmLWI0ZDUtNmIzYjM1MmQ0Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzNDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDJmYmVkZTQ1ZTU4ZjdmYzhhNzI5YTk4MzFlY2E1YjYxOGQ2MGZkMzhjYzFkN2U0ZTM5YjBkNjA4ODFmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnfGkSWR0wrVH4sGvnGZtnA60mc1omDGBGJDWezbL_0)
> 
> 同，老哥解决了吗

训练的时候传入的 `dataRoot` 应该是 `path/your/train/dataset/[all_images]/`目录，其中 `path/you/train/dataset/`目录下应该有三个目录：all_images, all_labels, mask，传入的目录是all_images
